; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:lilygo-t-display]
platform = espressif32
board = lilygo-t-display
framework = arduino
lib_deps = bodmer/TFT_eSPI@^2.5.43
build_flags =
  -DLOAD_TFT_ESPI_USER_CONFIG=1
  -DUSE_TFT

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<*> -<commands/command/tft/**>

[env:esp32-s3-dev]
platform = espressif32
board = esp32-s3-dev
framework = arduino
build_src_filter = +<*> -<commands/command/tft/**>

[env:esp32-c3-dev]
platform = espressif32
board = esp32-c3-dev
framework = arduino
build_src_filter = +<*> -<commands/command/tft/**>